import re


class SQLValidatorService:
    """
    Validates AI-generated SQL before it is sent to BigQuery.

    The validator allows only safe, read-only queries against
    approved supply-chain tables.
    """

    ALLOWED_TABLES = {
        "products",
        "inventory",
        "warehouses",
        "suppliers",
        "supplier_performance",
        "purchase_orders",
        "sales_orders",
        "demand_forecast",
        "shipments",
        "returns",
    }

    BLOCKED_KEYWORDS = {
        "INSERT",
        "UPDATE",
        "DELETE",
        "MERGE",
        "DROP",
        "ALTER",
        "CREATE",
        "TRUNCATE",
        "GRANT",
        "REVOKE",
        "CALL",
        "EXECUTE",
        "EXPORT",
    }

    def validate(self, sql_query: str) -> dict:
        """
        Validate a generated SQL query.

        Args:
            sql_query: SQL generated by Gemini.

        Returns:
            Dictionary containing:
            - is_valid: Whether the query is safe.
            - error: Validation error message, if any.
            - sql: Cleaned SQL query.
        """

        cleaned_sql = self._clean_sql(sql_query)

        if not cleaned_sql:
            return {
                "is_valid": False,
                "error": "The generated SQL query is empty.",
                "sql": "",
            }

        if cleaned_sql.upper() == "CANNOT_ANSWER":
            return {
                "is_valid": False,
                "error": (
                    "The question cannot be answered using the available "
                    "supply-chain schema."
                ),
                "sql": cleaned_sql,
            }

        if not self._starts_with_select_or_with(cleaned_sql):
            return {
                "is_valid": False,
                "error": (
                    "Only SELECT statements or WITH queries ending in "
                    "SELECT are allowed."
                ),
                "sql": cleaned_sql,
            }

        blocked_keyword = self._find_blocked_keyword(cleaned_sql)

        if blocked_keyword:
            return {
                "is_valid": False,
                "error": (
                    f"Unsafe SQL keyword detected: {blocked_keyword}. "
                    "Only read-only queries are allowed."
                ),
                "sql": cleaned_sql,
            }

        if self._contains_multiple_statements(cleaned_sql):
            return {
                "is_valid": False,
                "error": "Multiple SQL statements are not allowed.",
                "sql": cleaned_sql,
            }

        invalid_tables = self._find_invalid_tables(cleaned_sql)

        if invalid_tables:
            return {
                "is_valid": False,
                "error": (
                    "The query contains unapproved tables: "
                    + ", ".join(sorted(invalid_tables))
                ),
                "sql": cleaned_sql,
            }

        return {
            "is_valid": True,
            "error": None,
            "sql": cleaned_sql,
        }

    @staticmethod
    def _clean_sql(sql_query: str) -> str:
        """
        Remove whitespace and one optional trailing semicolon.
        """

        if not sql_query:
            return ""

        cleaned_sql = sql_query.strip()

        if cleaned_sql.endswith(";"):
            cleaned_sql = cleaned_sql[:-1].strip()

        return cleaned_sql

    @staticmethod
    def _starts_with_select_or_with(sql_query: str) -> bool:
        """
        Allow either:
        - SELECT ...
        - WITH ... SELECT ...
        """

        normalized_sql = sql_query.lstrip().upper()

        return (
            normalized_sql.startswith("SELECT")
            or normalized_sql.startswith("WITH")
        )

    def _find_blocked_keyword(self, sql_query: str):
        """
        Look for unsafe SQL commands as complete words.
        """

        normalized_sql = sql_query.upper()

        for keyword in self.BLOCKED_KEYWORDS:
            pattern = rf"\b{re.escape(keyword)}\b"

            if re.search(pattern, normalized_sql):
                return keyword

        return None

    @staticmethod
    def _contains_multiple_statements(sql_query: str) -> bool:
        """
        Reject multiple SQL statements separated by semicolons.

        A final semicolon is already removed by _clean_sql().
        Therefore, any remaining semicolon indicates another statement.
        """

        return ";" in sql_query

    def _find_invalid_tables(self, sql_query: str) -> set:
        """
        Extract fully qualified BigQuery table references and verify that
        their final table names are approved.

        Example:
        `project.dataset.inventory`
        """

        table_references = re.findall(
            r"`([^`]+)`",
            sql_query,
        )

        invalid_tables = set()

        for table_reference in table_references:
            table_name = table_reference.split(".")[-1]

            if table_name not in self.ALLOWED_TABLES:
                invalid_tables.add(table_name)

        return invalid_tables